# Generated by Django 5.1.8 on 2025-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_monitor', models.BooleanField(default=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
