# Generated by Django 5.1.8 on 2025-05-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Http',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('max_response_time', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_http', to='cf_account.account')),
            ],
            options={
                'verbose_name': 'HTTP 모니터링',
                'verbose_name_plural': 'HTTP 모니터링',
            },
        ),
        migrations.CreateModel(
            name='HttpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '성공'), ('timeout', '시간 초과'), ('keyword_not_found', '키워드 없음'), ('http_error', 'HTTP 오류'), ('connection_error', '연결 오류'), ('other_error', '기타 오류')], max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_http_result', to='cf_account.account')),
                ('http', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_result', to='monitor.http')),
            ],
            options={
                'verbose_name': 'HTTP 모니터링 결과',
                'verbose_name_plural': 'HTTP 모니터링 결과',
            },
        ),
    ]
