# Generated by Django 5.1.8 on 2025-05-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_account', '0001_initial'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='http',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_http', to='cf_account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='httpresult',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_http_result', to='cf_account.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='httpresult',
            name='http',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_result', to='monitor.http'),
        ),
    ]
