# Generated by Django 5.1.8 on 2025-05-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_account', '0001_initial'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['http', '-checked_at'], name='monitor_htt_http_id_4b5008_idx'),
        ),
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['status'], name='monitor_htt_status_46fe24_idx'),
        ),
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['http', 'status', '-checked_at'], name='monitor_htt_http_id_1a9e16_idx'),
        ),
    ]
