# Generated by Django 5.1.8 on 2025-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_http_account_httpresult_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='http',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
