# Generated by Django 5.1.8 on 2025-07-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_account', '0001_initial'),
        ('monitor', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='httpresult',
            name='monitor_htt_http_id_4b5008_idx',
        ),
        migrations.RemoveIndex(
            model_name='httpresult',
            name='monitor_htt_http_id_1a9e16_idx',
        ),
        migrations.RenameIndex(
            model_name='httpresult',
            new_name='status_idx',
            old_name='monitor_htt_status_46fe24_idx',
        ),
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['http', '-checked_at', 'status'], name='http_checked_status_idx'),
        ),
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['-checked_at'], name='checked_at_desc_idx'),
        ),
    ]
