# Generated by Django 5.1.8 on 2025-07-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_account', '0001_initial'),
        ('monitor', '0004_remove_httpresult_monitor_htt_http_id_4b5008_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='httpresult',
            name='http_checked_status_idx',
        ),
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['http', '-checked_at'], name='http_checked_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['status', '-checked_at'], name='status_checked_idx'),
        ),
    ]
