# Generated by Django 5.1.8 on 2025-07-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_httpresult_http_checked_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='httpresult',
            name='status_checked_idx',
        ),
    ]
