# Generated by Django 5.1.8 on 2025-07-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_account', '0001_initial'),
        ('monitor', '0006_remove_httpresult_status_checked_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='httpresult',
            name='checked_at_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='httpresult',
            new_name='monitor_htt_http_id_4b5008_idx',
            old_name='http_checked_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='httpresult',
            new_name='monitor_htt_status_46fe24_idx',
            old_name='status_idx',
        ),
        migrations.AddIndex(
            model_name='httpresult',
            index=models.Index(fields=['http', 'status', '-checked_at'], name='monitor_htt_http_id_1a9e16_idx'),
        ),
    ]
