# Generated by Django 5.1.8 on 2025-07-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_remove_httpresult_checked_at_desc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='httpresult',
            name='monitor_htt_http_id_1a9e16_idx',
        ),
    ]
