# Generated by Django 5.1.8 on 2025-07-29 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_httpresult_monitor_htt_http_id_1a9e16_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpLastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '성공'), ('timeout', '시간 초과'), ('keyword_not_found', '키워드 없음'), ('http_error', 'HTTP 오류'), ('connection_error', '연결 오류'), ('other_error', '기타 오류')], max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('http', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_result', to='monitor.http')),
            ],
        ),
    ]
