# Generated by Django 5.1.8 on 2025-07-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_httplastresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httplastresult',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
