# Generated by Django 5.1.8 on 2025-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_alter_httplastresult_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httplastresult',
            name='checked_at',
            field=models.DateTimeField(),
        ),
    ]
