# Generated by Django 5.1.8 on 2025-08-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_alter_httplastresult_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='http',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='정렬 순서'),
        ),
    ]
